
ALTER TABLE public.profiles 
ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS monthly_goal INTEGER DEFAULT 5,
ADD COLUMN IF NOT EXISTS activity_streak INTEGER DEFAULT 0;
